[platformio]
build_dir = ${sysenv.TEMP}/pio-p4-test-build

[env:esp32-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4-evboard-jtag # 32MB flash, 32MB PSRAM, built-in USB-JTAG enabled
framework = arduino
lib_archive = no
lib_deps =
    symlink://../package

extra_scripts =	post:scripts/fix_esp_builtin_upload.py

platform_packages =	tool-openocd-esp32 @ file://tools/openocd-esp32-p4

# Flash: 32MB QD, 32MB QSPI PSRAM
;board_build.flash_mode = qio
;board_upload.flash_size = 32MB
;board_upload.maximum_size = 33554432


board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
board_build.partitions = default.csv

build_flags =

# ---------- Core -----------------
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	
	-D CORE_DEBUG_LEVEL=0	
	-Og -ggdb3 -g3	



##### UPLOAD METHOD #####
	# [1] UPLOAD METHOD
;upload_protocol = esptool

	# [2] USB-JTAG built into ESP32-P4
upload_protocol = esp-builtin
debug_tool = esp-builtin
debug_speed = 5000
debug_init_break = tbreak setup

	# [3] UPLOAD METHOD
;upload_port = COM7
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder



##### BUILD TYPE #####
	# [A] RELEASE
build_type = debug

	# [B] DEBUG 
;build_type = debug
;monitor_port = COM2
