[platformio]
build_dir = ${sysenv.TEMP}/pio-lmt01-test-build

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 19200
lib_archive = no
lib_deps =
    symlink://../package

build_type = debug
